name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.GURITOGURA }}
          aws-secret-access-key: ${{ secrets.GURITOGURATOOKYAKUSAMA }}
          aws-region: ${{secrets.REGION}}

      - name: Install dependencies (if any)
        run: sudo apt-get install zip

      - name: Zip Lambda function and upload to S3
        run: |
          zip lambda_test1.zip lambda_test1.py

      - name: Deploy Lambda Function
        run: |
          aws lambda create-function \
            --function-name TestLambdaFunction \
            --role ${{ secrets.LAMBDA_EXECUTION_ROLE }} \
            --runtime python3.9 \
            --zip-file fileb://lambda_test1.zip \
            --handler lambda_test1.handler \
            --region ${{ secrets.REGION }}
